= RAP/RIF support

Adds functions to convert RAP to RIF and vice-versa with no dependency to a special AES implementation, so the develper is free to choose his preferred AES solution.
Additionally it provides the AES ECB/CBC 128-bit key to encrypt/decrypt RAP keys.

For RIF to RAP process the RIF with the function, then encrypt the intermediate result to get the RAP.
For RAP to RIF decrypt the RAP key, then process the intermediate result with the function to get the RIF.

== C Library for RAP/RIF
[source, c]
----
// AES key for RAP key encryption
const unsigned char * const rap_aes_key;

// functions
void rif2rap_rounds(const unsigned char * const in_rif_key, unsigned char * const out_unencrypted_rap_key);
void rap2rif_rounds(const unsigned char * const in_decrypted_rap_key, unsigned char * const out_rif_key);
----

== Python Module for RAP/RIF
_bytearray_ raprif.rap_aes_key::
AES ECB/CBC 128-bit key as bytearray.
_bytearray_ raprif.rif2rap_rounds(__bytes|bytearray__)::
Extra processing of RIF key.
_bytearray_ raprif.rap2rif_rounds(__bytes|bytearray__)::
Extra processing of decrypted RAP key.

[source, python]
----
from psntools import raprif  # access via raprif.
#import psntools.raprif  # access via psntools.raprif.
import binascii

binascii.hexlify(raprif.rap_aes_key)

rap_intermediate_bytes = raprif.rif2rap_rounds(rif_bytes)

rif_bytes = raprif.rap2rif_rounds(rap_intermediate_bytes)
----
